### ISSUE TITLE
Can you provide some feature which can be used to train the ubm and gmm ?

### ISSUE THREAD

**Issue by wuqiangch** [scelesticsiva/speaker_recognition_GMM_UBM#1]
Can you provide some feature which can be used to train the ubm and gmm ? Thanks!

**Comment by scelesticsiva** [comment]
MFCC features are used for speaker recognition since it capture information similar to human auditory system, I have included a script for extracting MFCC from audio into a csv file(instructions to use it are in README)

PS: It requires ffmpeg installed in your system for it to work
